### ISSUE TITLE
rawCssNamespace does not resolve the content as sass

### ISSUE THREAD

**Issue by danilosterrapid7** [QuickBase/babel-plugin-styled-components-css-namespace#18]
The new strategy for namespacing adds the wrapper as sass notation. I have only released now that styled components are not really sass. 

Given `rawCssNamespace: ['body .theme-light', '.theme-dark']` and styles:
```jsx
styled.div`
  display: block;
  min-width: 200px;

  &.myClass {
    /* some css */
  }
`
```
When the plugin namespace styles
Then it should not add namespace as wrapper

Current behaviour:
```jsx
styled.div`
  body .theme-light, .theme-dark {
    & {
      display: block;
      min-width: 200px;

      &.myClass {
        /* some css */
      }
    }
  }
`
```
Expected behaviour:
Current behaviour:
```
styled.div`
  body .theme-light &, .theme-dark & {
    display: block;
    min-width: 200px;
  }
  body .theme-light &.myClass, .theme-dark &.myClass  {
    /* some css */
  }
`
```

I will have a look at this weekend. I see to possible solutions:
* Introduce sass to parse it (which I like more);
* Create a module to analyse styles extracting the raw css as self and the rules scoped in its own module;

@nvanselow Sorry for that, it was good releasing as an alternative strategy. Let me know which solution you are up to, also, if you have a different solution. ;)

Thank you

**Comment by daniloster** [comment]
Hi @nvanselow really excited with this. I have a solution and I will put the PR soon.

**Comment by nvanselow** [comment]
Apologies for the delayed response. I was totally missing notifications for this repo. My own error, not the systems.

I look forward to the fix! I have been meaning to turn this new option on for our main repo now that it is merged, but haven't had the opportunity.

Which direction did you go with the potential PR?

**Comment by daniloster** [comment]
Hi @nvanselow , sorry taking long to answer back. I have been busy these days and I am going on holiday on Sartuday. So, I have sorted the simple case of having simple template string style without interpolation. But, I am still working on a way to sort the template with interpolation.

Sorted case:
```js
styled.div`
  font-size: 12px;

  label + & {
    font-weight: bold;
  }

  span + & {
    font-weight: italic;
  }
`
```

Not sorted case:
```js
styled.div`
  font-size: ${props => props.fontSize};

  label + & {
    font-weight: ${props => props.fontWeight};
  }

  ${props => props.parentContextSelector} + & {
    font-weight: italic;
  }
`
```

I will try to push what I have pretty soon, so, you can think about this case as well.

**Comment by daniloster** [comment]
The direction taken is: Creating a module to analyse styles extracting the raw css as self and the rules scoped in its own module;
