### ISSUE TITLE
Nothing transformed (usage with webpack and typescript)

### ISSUE THREAD

**Issue by Andruschenko** [QuickBase/babel-plugin-styled-components-css-namespace#19]
I tried to use the plugin together with webpack (babel-loader) and typescript, but wasn't successful.

With  the following `module.rules` part of my _webpack.config.js_ I receive no error but the plugin shows no effect, i.e. the CSS of styled components is not transformed at all:

```
        test: /\.tsx?$/,
        exclude: path.resolve(__dirname, '../node_modules'),
        loader: 'babel-loader',
        options: {
            plugins: ['@quickbaseoss/babel-plugin-styled-components-css-namespace']
        }
```

When adding `{ cssNamespace: 'moreSpecific' }`, that is:

```
        test: /\.tsx?$/,
        exclude: path.resolve(__dirname, '../node_modules'),
        loader: 'babel-loader',
        options: {
            plugins: [
                '@quickbaseoss/babel-plugin-styled-components-css-namespace',
                { cssNamespace: 'moreSpecific' }
            ]
        }
```

...I get the following error:

```
Module build failed: Error: Plugin 1 specified in "base" provided an invalid property of "cssNamespace"
```

_Any ideas?_

**Versions of tools**:

typescript: `^3.0.1`
webpack: `^2.3.3`
babel-loader: `^7.1.5`
babel-plugin-styled-components-css-namespace: `^0.1.1`

**Comment by danilosterrapid7** [comment]
You still need to have the `styled-components` plugin in that list...
Also, you were assigning the plugin incorrectly. Plugins prop expects an array, then, if you want to customise a specific plugin passing config values, you need to wrap the plugin into another array.
```
            plugins: [
                ['@quickbaseoss/babel-plugin-styled-components-css-namespace', { cssNamespace: 'moreSpecific' }],
                "styled-components"
            ]
```
