### ISSUE TITLE
Fix Known Issue with Sibling Selector

### ISSUE THREAD

**Issue by Pczek** [QuickBase/babel-plugin-styled-components-css-namespace#24]
Hi I'm using `styled-components` in my current project and want to use this babel plugin as suggested by the official docs to prevent third-party styling of my components when embedded as a widget.

The styled components in this projects make quite some use of the & and sibling operator ~ which is not working and a known issue as stated in the docs. Is there any ambition to fix this in a future release as it seems to be fixed when using the `rawCssNamepsace` option? Unfortunately the `rawCssNamespace` option does not work in my project and my `webpack dev server` is not starting, it seems to be stuck in an infinite loop. I tried to debug it but till now I had no luck. Any hints are highly appreciated.

**Comment by boris-hocde** [comment]
Hi, jumping in :)
First thanks for this awesome plugin!

I had a similar issue with webpack never ending building when switching from `cssNamespace` to `rawCssNamespace`. It took me ages to isolate the issue, but I achieved to have a reproducible case.

The issue only occurs when the parsed style is big enough. It looks like its content does not really matter.
The build seems to be stuck into [startsWithSelfReference](https://github.com/QuickBase/babel-plugin-styled-components-css-namespace/blob/master/src/visitors/cssNamespace.js#L12).
In src/index.js, if you remove any of the 3 CSS lines, the build will work.

## How to reproduce

Create the following files

### /src/index.html

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>React and Webpack4</title>
</head>

<body class="root">
    <section id="index"></section>
</body>
</html>
```

### /src/index.js

```js
import React from "react";
import ReactDOM from "react-dom";
import styled from 'styled-components'

const Index = () => {
  const Component = styled.div`
      background-color: blue;
      color: white;
      font-weight: bold;
    `;

  return <Component>Hello React!</Component>;
};

ReactDOM.render(<Index/>, document.getElementById("index"));
```

### /package.json

```json
{
  "name": "styled-namespace-webpack",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack --mode production"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@quickbaseoss/babel-plugin-styled-components-css-namespace": "^0.1.1",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.5",
    "babel-plugin-styled-components": "^1.8.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "html-webpack-plugin": "^3.2.0",
    "webpack": "^4.26.0",
    "webpack-cli": "^3.1.2"
  },
  "dependencies": {
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "styled-components": "^4.1.1"
  }
}
```

### webpack.config.js

```js
const HtmlWebPackPlugin = require("html-webpack-plugin");

const htmlPlugin = new HtmlWebPackPlugin({
  template: "./src/index.html",
  filename: "./index.html"
});

module.exports = {
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            babelrc: false,
            presets: ['react', 'env'],
            plugins: [
              [
                '@quickbaseoss/babel-plugin-styled-components-css-namespace',
                { rawCssNamespace: '.root' },
              ],
              'styled-components'
            ],
          }
        }
      }
    ]
  },
  plugins: [
    htmlPlugin
  ]
};
```

Then run `npm run build`

**Comment by nvanselow** [comment]
Thanks for the reproducible case. We'll have to take a look. Apologies for the incredibly delayed response. I guess I don't get notifications for new issues and wasn't checking regularly.
