### ISSUE TITLE
Duplicating ClassName Multiple Times

### ISSUE THREAD

**Issue by zachhardesty7** [QuickBase/babel-plugin-styled-components-css-namespace#32]
Hey man! This has been a super useful plugin for working with styled-components and 3rd party libraries but sometimes it would be super helpful to allow the className to be duplicated more than once. I tried running the plugin in Babel twice but that didn't work. Any thoughts?

**Comment by nvanselow** [comment]
I'm happy to hear it has been useful.

Have you tried setting the css namespace to multiple `&` to get the effect you wanted?

`["@quickbaseoss/babel-plugin-styled-components-css-namespace", {"cssNamespace": "&&&"}]

**Comment by zachhardesty7** [comment]
@nvanselow I don't believe this worked on the older 0.x.x version and I had some issues updating (as documented in #33). It appears that this works now and is super helpful, thanks!

**Comment by nvanselow** [comment]
Excellent. I'm glad that solved your use case. I'll have to take a look at the problems you identified in the other issue so you can use that latest version.

**Comment by erikthedeveloper** [comment]
This is exactly what we've been needing! Thanks for posting that as a solution here @nvanselow 😃

I imagine this has got to be a fairly common scenario when integrating styled-components into existing/legacy projects. For example, in my case we are up against some rather gnarly legacy CSS selectors such as `#someId .grossly .nested section input {}` 😅...

We've gotten around this in a different way in the past by hacking on the idea of a custom namespace that required all "new" components to be nested under `.some.selector.for.specificity`, but this `&&&` solution is much more ideal.

📝 This seems that have done the trick for us 🙏🏽

```
{
  // ...
  "plugins": [
    [
      "@quickbaseoss/babel-plugin-styled-components-css-namespace",
      {"cssNamespace": "&&&"}
    ],
    "babel-plugin-styled-components",
    // ...
    ]
}
```

**Comment by erikthedeveloper** [comment]
📝 PR submitted documenting this in the README [Add README section about "Increasing Specificity" #36](https://github.com/QuickBase/babel-plugin-styled-components-css-namespace/pull/36)

**Comment by nvanselow** [comment]
Thanks for opening that as a PR @erikthedeveloper!
