### ISSUE TITLE
Unknown word

### ISSUE THREAD

**Issue by zachhardesty7** [QuickBase/babel-plugin-styled-components-css-namespace#33]
Having an issue since upgrading to the new version. This plugin is failing with the following message:

```
There was a problem adding namespaces to this CSS. Error: <css input>:5:5: Unknown word
 CSS: 
  && {
    fake-element-placeholder
    fake-element-placeholder
    transition: ease-in-out 50ms;

    fake-element-placeholder
    &:hover {
      transition: ease-in-out 100ms;
    }
  }
```

It's failing with the repo here: https://github.com/zachhardesty7/semantic-styled-ui
I'm currently working on reducing the factors that could cause this and getting a minimal reproducible test case going but as of now, it should be reproducible with the above files!

**Comment by zachhardesty7** [comment]
UPDATE: found 2 bug conditions that will break the babel transformation, guaranteed. Mind you, these all compile and function properly with the regular babel plugin for styled-components. Hope these help with bug fixing! An error that states which file the CSS came from would be super helpful. Let me know if I can help with these, may try to write a pull request later.

Any sort of comment inline in the style definition where the next line starts with a nested template expression. Adding a `;` after the comment works but produces stylelint errors. Ex:
```
const StyledComponent1 = styled.div`
  /* comment */
  ${'color: blue'};
`
```

Any nested template literals that don't have a trailing `;`, regardless of if they always return a semicolon. Ex:
```
const StyledComponent2 = styled.div`
	${props => 'color: blue;'}
`
```

**Comment by nvanselow** [comment]
Thanks for the heads up  and the possible files to repro!

**Comment by supadupdip** [comment]
Is there any update on this? Seems like a pretty big deal considering the whole thing about styled components is the ability to use javascript inline

**Comment by nvanselow** [comment]
@supadupdip - Not yet. However, the only inline js that should be affected currently are cases like those demonstrated in https://github.com/QuickBase/babel-plugin-styled-components-css-namespace/issues/33#issuecomment-472494080

E.g., the following should work as expected:

```
const StyledComponent2 = styled.div`
	color: ${props => isSuccess  ?  'green' : 'red'};
```

The following fixtures are currently passing for this plugin which show using  inline js:  https://github.com/QuickBase/babel-plugin-styled-components-css-namespace/blob/master/src/tests/fixtures/complex_styled_component.js

The next block of time I have available to work on this plugin is 5/24 where I hope to close out many  of the open issues. However, PRs are always welcome.

**Comment by nvanselow** [comment]
The two reproducible cases @zachhardesty7 mentioned above should be fixed  in this PR: https://github.com/QuickBase/babel-plugin-styled-components-css-namespace/pull/39

Once  approved, I'll get a new release candidate out for  further testing in the wild.
